-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  invoice_items

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  invoice_id BIGINT NOT NULL,
  line_no INTEGER NOT NULL,
  description TEXT NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  quantity INTEGER NOT NULL,
  tax_rate NUMERIC(5,2) NOT NULL,
  tax_amount NUMERIC(12,2) NOT NULL,
  line_total NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_invoice_line UNIQUE (invoice_id, line_no),
  CONSTRAINT chk_invoice_items_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_invoice_items_qty CHECK (quantity > 0),
  CONSTRAINT chk_invoice_items_nonneg CHECK (unit_price >= 0 AND tax_amount >= 0 AND line_total >= 0)
);
